pipeline:
  identifier: Build_pushkarbhadang12_GoPipelineRepository_1704021732959
  name: Build GoPipelineRepository
  orgIdentifier: default
  projectIdentifier: TestPipeline
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1703314950386
        repoName: pushkarbhadang12/GoPipelineRepository
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: run unit tests
                  spec:
                    connectorRef: account.harnessImage
                    image: golang:1.15
                    shell: Sh
                    command: |-
                      set +e
                      go get gotest.tools/gotestsum
                      gotestsum --format*standard-verbose --junitfile unit-tests.xml
                      exit 0
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "*.xml"
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
